apiVersion: v1
kind: Service
metadata:
  name: open-webui-tcp
  namespace: open-webui
spec:
  type: LoadBalancer
  ports:
  - name: web-ui
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: open-webui
