---
cluster:
  name: meta-monitoring-tutorial

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push

clusterEvents:
  enabled: true
  collector: alloy-logs
  namespaces:
  - cert-manager
  - default
  - jupyter
  - keycloak
  - kube-system
  - monitoring
  - nfs-system
  - node-feature-discovery
  - nvidia-device-plugin
  - ollama
  - open-webui
  - rabbitmq-system
  - redis

nodeLogs:
  enabled: false

podLogs:
  enabled: true
  gatherMethod: kubernetesApi
  collector: alloy-logs
  labelsToKeep: ["app_kubernetes_io_name","container","instance","job","level","namespace","service_name","service_namespace","deployment_environment","deployment_environment_name"]
  structuredMetadata:
    pod: pod  # Set structured metadata "pod" from label "pod"
  namespaces:
  - cert-manager
  - default
  - jupyter
  - keycloak
  - kube-system
  - metallb-system
  - monitoring
  - nfs-system
  - node-feature-discovery
  - nvidia-device-plugin
  - ollama
  - open-webui
  - rabbitmq-system
  - redis
  - loki
  - alloy


clusterMetrics:
  enabled: false

# Collectors
alloy-singleton:
  enabled: false

alloy-logs:
  enabled: true
  # Required when using the Kubernetes API to pod logs
  alloy:
    mounts:
      varlog: true
    clustering:
      enabled: true

alloy-profiles:
  enabled: false

alloy-receiver:
  enabled: false

service:
  type: LoadBalancer
