Name:         homepage
Namespace:    default
Labels:       app.kubernetes.io/name=homepage
Annotations:  <none>

Data
====
bookmarks.yaml:
----
- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/


custom.css:
----


custom.js:
----


docker.yaml:
----


kubernetes.yaml:
----
mode: cluster


services.yaml:
----
- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is ðŸ˜Ž


settings.yaml:
----


widgets.yaml:
----
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
    network: default
- search:
    provider: duckduckgo
    target: _blank



BinaryData
====

Events:  <none>
