# the proxy pod.
hub:
  nodeSelector:
    kubernetes.io/hostname: turing-five
  db:
    pvc:
      accessModes:
        - ReadWriteMany
      storage: 10Gi
      storageClassName: jubhub-nfs-client
  service:
    type: LoadBalancer


singleuser:
  extraResource:
    limits:
      nvidia.com/gpu: "1" 
  nodeSelector:
    kubernetes.io/hostname: turing-five
  storage:
    type: dynamic
    capacity: 2Gi
    dynamic:
      storageClass: jubhub-nfs-client
#  profileList:
#    - display_name: "GPU Server"
#      description: "Spawns a notebook server with access to a GPU"
#      kubespawner_override:
#        extra_resource_limits:
#          nvidia.com/gpu: "1" 
#        nodeSelector:
#          kubernetes.io/hostname: turing-five                 

# scheduling relates to the user-scheduler pods and user-placeholder pods.
scheduling:
  userScheduler:
    nodeSelector: 
      kubernetes.io/hostname: turing-five

# prePuller relates to the hook|continuous-image-puller DaemonsSets
prePuller:
  hook:
    nodeSelector: 
      kubernetes.io/hostname: turing-five

ingress:
  enabled: false


httpRoute:
  enabled: false
