# the proxy pod.
hub:
  nodeSelector:
    jupyter: "true"
  db:
    pvc:
      accessModes:
        - ReadWriteMany
      storage: 10Gi
      storageClassName: jubhub-nfs-client
  service:
    type: ClusterIP

# scheduling relates to the user-scheduler pods and user-placeholder pods.
scheduling:
  userScheduler:
    nodeSelector: 
      jupyter: "true"

# prePuller relates to the hook|continuous-image-puller DaemonsSets
prePuller:
  hook:
    nodeSelector: 
     jupyter: "true"

ingress:
  enabled: false


httpRoute:
  enabled: false


