# values.yaml
nfs:
  server: 192.168.1.83
  path: /mnt/ssd/postgres 

storageClass:
  name: nfs-client
  provisionerName: k8s-sigs.io/docker-nfs-subdir-external-provisioner 

nodeSelector:
  nfs-provisioner: "true"
